version: '3.6'
services:
  web:
    image: web
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
    - "2087:5001"
    volumes:
    - .:/usr/src/app
    command: [ "python3","-u", "src/web-server.py"]
    networks:
      - redis-net
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - redis-net

networks:
  redis-net:

volumes:
  redis-data: