version: '3.6'
services:
  web:
      image: web
      build: 
        context: . 
        dockerfile: Dockerfile
      ports:
      - "5001:5001"
      volumes:
      - .:/usr/src/app
      command: [ "python", "src/web-server.py"]
  redis:
      image: "redis:alpine"