version: '3.6'
services:
  web:
    image: web
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
    - "14769:14769"
    volumes:
    - .:/usr/src/app
    command: [ "gunicorn","-c","gunicorn_cfg.py","web-server:app"]
    networks:
      - redis-net
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - redis-net
  caddy:
    image: "wemakeservices/caddy-docker:latest"
    volumes:
      - ./caddy/path:/root/.caddy  # to save certificates on disk
      - ./caddy/Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    depends_on:
      - web
networks:
  redis-net:

volumes:
  redis-data: